//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.10 at 08:32:52 AM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ucll.be/java/com/example/todo")
package example.com.soap.model;
